name: Auto Rebuild on Binding Updates

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'c_data_python_bindings'
      - '.gitmodules'

jobs:
  trigger-rebuild:
    name: Trigger rebuild after binding update
    runs-on: ubuntu-latest

    steps:
      - name: Trigger main build workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Wait a moment for the push to complete
            await new Promise(resolve => setTimeout(resolve, 5000));

            // Trigger the main build workflow
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: context.ref
            });

            console.log('Triggered rebuild after binding update');